name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Generate key
      run: php artisan key:generate

    - name: Run Migrations
      run: php artisan migrate

    - name: Execute tests (PHPUnit)
      run: vendor/bin/phpunit
